apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap               
data:
  default.conf:
    upstream backend {
      server service-app1:8080 weight=7;
      server service-app2:8080 weight=3;
    }

    server {
        location / {
            proxy_pass http://backend;
        }
    }
